# This workflow will build a Java project with Gradle
name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: eltitomarian/test-uax
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  # - uses: mr-smithers-excellent/docker-build-push@v6
  #   name: Build & push Docker image
  #   with:
  #     image: repo/image
  #     tags: v1, latest
  #     registry: registry-url.io
  #     dockerfile: Dockerfile.ci
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}
         
